language: java

jdk: openjdk11

addons:
  sonarcloud:
    organization: "nmoreaud"
    token:
      secure: "icVWIxR87SfgBwPi31vT8//pdL6fnFJdlJRkPkFqxhcgyROR7uN9O+veBaWvxUOOAhTL3jO89jauvLCoHivH4TwlNT+28SrD2orAaagA8er8+AZ5cNM/FRuhm+xYl3YFylCKMs+ojq+gv7AdTGQpKyMt/PXirtd6XU+EX5h9xrGv3WVpXXfqMJqrEM6PVxUOY9ZDZF57hfDibk6S8lxEd5vL4Q0DMLjllyXSHCCUngLI8svrGz/EJnutQszMOglIpkTEF4XBAjym/zDucYTWMUKfJJ2LiZfXf5wgz2k/E6JsZKdiYzCUWUwVoWv1QWiuyyGJ+giPn8laT9z/wSu4HEcChqAFSa4tR4O4hGroxoUqe1sotObYJKKTDRVDlgBnlXh0qPOgVgQ4nA+xtWJzub62k5Z6pwJTkFauKtVK/RCXXzvnWEPSHxLhcbTRSr4sA3uEP0yAAwUWfywOD+nSSzvuK2IeIy7Yte3+wkucabjTIMHYE4m5VEmXeVjxWZ55RvvJ3grjyDh+s5+/UARx7bY6/9OHKFG+B/dU8lhz9O9XCQtSXYw7ap1cA6w/0Ne4yV3DDihCstW0RV2Ps7US13wa+b/YStsHHJeA0fpjbGp7uR4ztqbk1hBbK7Joh4FC19Ckf9ysWHShI3shOzIljpVDXIvx5t74olrpwiRfi74="
#cache:
#  directories:
#    - $HOME/.m2

script:
  - ./mvnw clean install sonar:sonar -Dsonar.projectKey=nmoreaud_OpenwisTraining

notifications:
  email:
    on_success: always
    on_failure: always
    #recipients:
    #  secure: "AAxkpl8E8xdjWFmreQBbr28DFiqBDXs50/r78qEak1SFJxZ48DJr9kHD7/d/7t5cdX2K4oIjDoA7CUn/K0seun28piHy2RyqBZW7kfSFIj8PmzGdG9gY5b+bme4rBZwFgGvr5UDvs8+fz9CxJu0Dn7kLY1kO5Rz7fU7C55vi2GPoWZ8Jlk5fwFbaCx/PuSfCTwxu9kO0Bfs5syAEMK4etWA6QHRuqt8CBZoEQdMLuDXgFdep6NcKUx+h7b0kNIIhS1YP7hW5GszlK/MtmFmlw0PtnLaQYKnI1z9TYO7Z1G140g4al4bCgrVDOfYDicQXGo3Q29w0xwHP7te8lKcMCWZgmtT32RLVnj6vsgpBpGCaw4/kEY+y/ZfvzqBYhCRsiMdLsKvAeg/Daf/foGBaJ/Hfuh7nerie9P1if6jB5TIHqAJ2jBhGmRq5TErOIS+q0QHDBB9g555KTfZOkqhLdJ9nwSxELNUoDQR5RO9cqQiFi3nt2ToxB73AFgzXcb+3sVeZaeZP5aYQiF4QuimBJtS6PuExziMV4d6vPhqrHZVhkKnx9mdlZWh/BxpMgNStups4TcDgFl39bAJVaQzmZGzV0pCrwOheNwpUUBHLjQQ3gciMDXCli4cV9hjcdhvFQlLRrdtcyg9bW7wGXVQek3UsgkwU6GRjvRbzyYm/Fhw="
