language: java
jdk: openjdk11
script:
  - ./mvnw clean install sonar:sonar -Dsonar.projectKey=nmoreaud_OpenwisTraining

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: "AAxkpl8E8xdjWFmreQBbr28DFiqBDXs50/r78qEak1SFJxZ48DJr9kHD7/d/7t5cdX2K4oIjDoA7CUn/K0seun28piHy2RyqBZW7kfSFIj8PmzGdG9gY5b+bme4rBZwFgGvr5UDvs8+fz9CxJu0Dn7kLY1kO5Rz7fU7C55vi2GPoWZ8Jlk5fwFbaCx/PuSfCTwxu9kO0Bfs5syAEMK4etWA6QHRuqt8CBZoEQdMLuDXgFdep6NcKUx+h7b0kNIIhS1YP7hW5GszlK/MtmFmlw0PtnLaQYKnI1z9TYO7Z1G140g4al4bCgrVDOfYDicQXGo3Q29w0xwHP7te8lKcMCWZgmtT32RLVnj6vsgpBpGCaw4/kEY+y/ZfvzqBYhCRsiMdLsKvAeg/Daf/foGBaJ/Hfuh7nerie9P1if6jB5TIHqAJ2jBhGmRq5TErOIS+q0QHDBB9g555KTfZOkqhLdJ9nwSxELNUoDQR5RO9cqQiFi3nt2ToxB73AFgzXcb+3sVeZaeZP5aYQiF4QuimBJtS6PuExziMV4d6vPhqrHZVhkKnx9mdlZWh/BxpMgNStups4TcDgFl39bAJVaQzmZGzV0pCrwOheNwpUUBHLjQQ3gciMDXCli4cV9hjcdhvFQlLRrdtcyg9bW7wGXVQek3UsgkwU6GRjvRbzyYm/Fhw="

addons:
  sonarcloud:
    organization: "nnmoreaud"
    token:
      secure: "A79hklSptzv94ernga7FKguyXZ7DPzZ/DPdjcW2tLxh6sP/sN0CushJulM/DzVj+wUgnpkHZEYbqPYZu5i18F/YV9edQYTMXC34YoVXMOBnIx8DxjeKmKhvTTAac/kVTTV04vFaFaQVHVyPBEZEzMWrKsdyuGtU7kukH6n8rBG9cC1Whm1bovz3bhdtdY1SsI906Rj1u0PsWlmsz9fHnIqY1+hiIHzrAKwJ6tU3u1lmi3nzZV8nFlXpSzeiDWoVy2OTm0d04IV0b/GonQmzl3xxtG5IUBOslrpSBNmcEdP2qTAuNPEca/99Q0fr7aAhNaolwdyxIyX2TH20p9cv7Zij39YhW/cFLZCUUIoT/ojNebMehflzQSxPg0vlc0PRu62ojmBC/RCGdVYPc3JEZBU9LG1iSNibXojEsXIAyWwDAjAxnSdhfYkVzMhi1S56NyqDWm8Ppjmaeb4qXlxWucpDDUKnuW/2PBH9aA6zHzXjuESlJjRhJjSK2xwGim8hEKdySMEPwPrtPcRCqxMUMEY6FGMFIDWDY/q0ytbaDbC4+/5QsdEVxunAYlJsMEju9RFE16g4ToxjKLtlBhn2SyTgJtLroOjYqtgQzusS28X2QJihSqPT/5hm3dVSNyqkERhvlMl3CfOjKM9+qeRE4Nu45yfpk+fYY/LCZKG8WiWw="
