language: java

jdk: openjdk11

addons:
  sonarcloud:
    organization: "nmoreaud"
    token:
      secure: "VPq7W15feeWUpnYo4TfB75qtqFsDmeDjiESx4lHwIe4oLvAWlvyMyVghKP32wS34bcgKufieNvOFZKzFMxj1kKM9z/1tO0FkMzJJ1TLhWN9/4TOqqxvYR9fwMFkulFH393ismYaEEfPs88hqKbHYApr9PbYaTPTpVsWETt6d/fB78B3ONhiUB1iywky2PPdh3vFw5G6FvDARlDBYYyrHTj5n3Mv+nGq5+qkN/Hbmck2GKw6osQIpADboVs7FlVbPulflx/34VuK9vkwnXETUDbbcrlfrl6j41GwhvkDoHoQpEvGnwOLfqVfaE6NrJVioWKNuiPyvek+b7gzat4jRRosSYTOENITaocfuur1hZrO6v8uBCkykyqiN3ZoLC1SUtN2Milu2Anwv2GeluxThmPnnWPok6AQ7qcjJSpEHG5ly17fPLp9iwctxFotjD/yt3JCBvCZF27R+3mBZT5EQeWUu/mrCC7m0rfQz+wOQs44FPcMihgfG8tjdn7y3NdtGE5pVVHxxuWWr+aARXhPb8wBPYndd/k9hM27UiYH6kfdra8dBw4BoldLB9ZS5oT99ompomilmmNipFSKZI1QqnrWDJP1OK2FRAwCcbvnzLQHFD8ELLOpFKIrRf1TWkkNm7ZhTu8jy1HmvSRRQnzY/V4uCbGcJpeRip0YWNNHJvIM="

script:
  - ./mvnw clean install sonar:sonar -Dsonar.projectKey=nmoreaud_OpenwisTraining

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: "AAxkpl8E8xdjWFmreQBbr28DFiqBDXs50/r78qEak1SFJxZ48DJr9kHD7/d/7t5cdX2K4oIjDoA7CUn/K0seun28piHy2RyqBZW7kfSFIj8PmzGdG9gY5b+bme4rBZwFgGvr5UDvs8+fz9CxJu0Dn7kLY1kO5Rz7fU7C55vi2GPoWZ8Jlk5fwFbaCx/PuSfCTwxu9kO0Bfs5syAEMK4etWA6QHRuqt8CBZoEQdMLuDXgFdep6NcKUx+h7b0kNIIhS1YP7hW5GszlK/MtmFmlw0PtnLaQYKnI1z9TYO7Z1G140g4al4bCgrVDOfYDicQXGo3Q29w0xwHP7te8lKcMCWZgmtT32RLVnj6vsgpBpGCaw4/kEY+y/ZfvzqBYhCRsiMdLsKvAeg/Daf/foGBaJ/Hfuh7nerie9P1if6jB5TIHqAJ2jBhGmRq5TErOIS+q0QHDBB9g555KTfZOkqhLdJ9nwSxELNUoDQR5RO9cqQiFi3nt2ToxB73AFgzXcb+3sVeZaeZP5aYQiF4QuimBJtS6PuExziMV4d6vPhqrHZVhkKnx9mdlZWh/BxpMgNStups4TcDgFl39bAJVaQzmZGzV0pCrwOheNwpUUBHLjQQ3gciMDXCli4cV9hjcdhvFQlLRrdtcyg9bW7wGXVQek3UsgkwU6GRjvRbzyYm/Fhw="
