language: java

jdk: openjdk11

addons:
  sonarcloud:
    organization: "nnmoreaud"
    token:
      secure: "KINKRDROKdalLtNEyBvdJSNG97bqBZWVHkrD+xARXnLiujqokBkO4+EI9IvfvbayHw8rmyRdjQnU7r49nN0FHG8B83AZ9zW6oTOfFSA1IDvU2NpzqAfpPPh65Nr5YCZUrTPcSNgGWNcmeaCSFJZ07N59Jb0wWIrsHkVDHzRERc007rureydav6iD+t3qf+tkp/xJFSQ+O9stKMOWf9l5aGHDT2BfTgH0i4qOUqVs56o2VJLWPIWeg9MvF9Gz+lqvqW7QLc/V+t3oTKzmXnzkR7UN5UcRo6aFXH0lzp3+kSOJRTDRXxauXB5dx1PmWWhyG5+aoe3lDwEFK6aRVgRtTsya9uYWihY4dVUwzYAn7wHY+kdFOkE50hRivLZmC/nziYe53T23yjTtT12x2TClG40KoGjMM0VB4yYOozWZMjVUJMkUWXvmUUGfYLB+Z0CEAUQhra8yT58rBf7cNHyQjom+QXTObEUb6Of4Ejt62XFhFKwc+JvCiNGftbVLQ8+16n50Emlh9oQujwvBjUGJoyW9/bCA8ifN/LShwN82GDQbw7Jo3w744UJ2wX0g+bH94+whKgeTUl7ANpHlLwM8c4lyoVU66jFIXN8x0wUN73NXnM8BXnX+KTTOrqeABWGPIu86I3uDtqOwTzf1LPq1mHg8LFL8jHLJBf51oZF/ujQ="

script:
  - ./mvnw clean install sonar:sonar -Dsonar.projectKey=nmoreaud_OpenwisTraining

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: "AAxkpl8E8xdjWFmreQBbr28DFiqBDXs50/r78qEak1SFJxZ48DJr9kHD7/d/7t5cdX2K4oIjDoA7CUn/K0seun28piHy2RyqBZW7kfSFIj8PmzGdG9gY5b+bme4rBZwFgGvr5UDvs8+fz9CxJu0Dn7kLY1kO5Rz7fU7C55vi2GPoWZ8Jlk5fwFbaCx/PuSfCTwxu9kO0Bfs5syAEMK4etWA6QHRuqt8CBZoEQdMLuDXgFdep6NcKUx+h7b0kNIIhS1YP7hW5GszlK/MtmFmlw0PtnLaQYKnI1z9TYO7Z1G140g4al4bCgrVDOfYDicQXGo3Q29w0xwHP7te8lKcMCWZgmtT32RLVnj6vsgpBpGCaw4/kEY+y/ZfvzqBYhCRsiMdLsKvAeg/Daf/foGBaJ/Hfuh7nerie9P1if6jB5TIHqAJ2jBhGmRq5TErOIS+q0QHDBB9g555KTfZOkqhLdJ9nwSxELNUoDQR5RO9cqQiFi3nt2ToxB73AFgzXcb+3sVeZaeZP5aYQiF4QuimBJtS6PuExziMV4d6vPhqrHZVhkKnx9mdlZWh/BxpMgNStups4TcDgFl39bAJVaQzmZGzV0pCrwOheNwpUUBHLjQQ3gciMDXCli4cV9hjcdhvFQlLRrdtcyg9bW7wGXVQek3UsgkwU6GRjvRbzyYm/Fhw="
