language: java

jdk: openjdk11

addons:
  sonarcloud:
    organization: "nnmoreaud"
    token:
      secure: "HQOKCGKmUZROhkDgt5d4p+e9m/aniE1s4ZJgLtxmI/iBXRxejOS9oKuOzya1sLDwwFl8EtHdBN0xGzVUBM+GEfjyBJwbXRu++YpbwSb4v2P1tBdnO69WUqNVXiyuakBsWfqcJxWlafHd/pR81Ue9rzIaMMZ4APAucBXDfgB5Hp8r3fwx7noOUTRvrUQ9L9fv7JkTvzdvHPk4OG6T5ewNNB2+/VHvJbp+065bIqXgEim2hSZgthNBfGY3CXTM8jtasmXpaS7VB4RxkAhLrhOT5z4gN8DmDsZBuBnOrDuWXQ9FJ1v7Kr85BhspykfCFumFAeSeMyzXxr4KDPPSRNf5NWwy3XsQpOjI8IfVZJSLH5q+Sxdh11G9++3ZO66oxLfeNAgEezt2oQyiL/LlwRsYyvq9Iaj5jHV8KwN5JmwtVe7SaYuaKIG2qJNdBdKWDp1IQ1h7MLDCk/IATNaQeblw7EHrLgcU8YVFs49VpPbknUrj4fJU8Hv7mqvV6bzbLWUyxuchBnfi+LXEaimeTDpsVQnbjaOW6x34P7LX7EXlwQMWY7Ldj2lHveWfmg7pslRLWRULTG4UeICltCwlIxBYJuvCLza2+pADkrBnIBEay0lG0apdkfNXmusxtXvoeP87zLtvN23RJkGaJZcFIem6bVj/DhQB0olNAGA0ycAvCQ0="

script:
  - ./mvnw clean install sonar:sonar -Dsonar.projectKey=nmoreaud_OpenwisTraining

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: "AAxkpl8E8xdjWFmreQBbr28DFiqBDXs50/r78qEak1SFJxZ48DJr9kHD7/d/7t5cdX2K4oIjDoA7CUn/K0seun28piHy2RyqBZW7kfSFIj8PmzGdG9gY5b+bme4rBZwFgGvr5UDvs8+fz9CxJu0Dn7kLY1kO5Rz7fU7C55vi2GPoWZ8Jlk5fwFbaCx/PuSfCTwxu9kO0Bfs5syAEMK4etWA6QHRuqt8CBZoEQdMLuDXgFdep6NcKUx+h7b0kNIIhS1YP7hW5GszlK/MtmFmlw0PtnLaQYKnI1z9TYO7Z1G140g4al4bCgrVDOfYDicQXGo3Q29w0xwHP7te8lKcMCWZgmtT32RLVnj6vsgpBpGCaw4/kEY+y/ZfvzqBYhCRsiMdLsKvAeg/Daf/foGBaJ/Hfuh7nerie9P1if6jB5TIHqAJ2jBhGmRq5TErOIS+q0QHDBB9g555KTfZOkqhLdJ9nwSxELNUoDQR5RO9cqQiFi3nt2ToxB73AFgzXcb+3sVeZaeZP5aYQiF4QuimBJtS6PuExziMV4d6vPhqrHZVhkKnx9mdlZWh/BxpMgNStups4TcDgFl39bAJVaQzmZGzV0pCrwOheNwpUUBHLjQQ3gciMDXCli4cV9hjcdhvFQlLRrdtcyg9bW7wGXVQek3UsgkwU6GRjvRbzyYm/Fhw="
